# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/leoniddukov/UI/converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(440, 220))
        MainWindow.setMaximumSize(QtCore.QSize(440, 220))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 70, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(62, 62, 62);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 70, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(62, 62, 62);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 361, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 131, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 160, 191, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(62, 62, 62);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 160, 60, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ui to Py"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Ui to Py converter</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать файл"))
        self.pushButton_2.setText(_translate("MainWindow", "Конвертировать"))
        self.label_2.setText(_translate("MainWindow", "Выбраный файл: "))
        self.label_3.setText(_translate("MainWindow", "Название .py файла"))
        self.label_4.setText(_translate("MainWindow", ".py"))

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    g_file_path = str()
    g_file_name = str()
    g_file_ext = str()
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.pushButton.clicked.connect(self.selfile)
        self.pushButton_2.clicked.connect(self.convert)
    def selfile(self):
        file_path, _ = QFileDialog.getOpenFileName(self, 'Open Ui File')
        self.label_2.setText(f"Выбраный файл: {file_path}")
        file_name, file_ext = os.path.splitext(file_path)
        global g_file_path
        global g_file_name
        global g_file_ext
        g_file_name = file_name
        g_file_ext = file_ext
        g_file_path = file_path
    def convert(self):
        global g_file_path
        global g_file_name
        global g_file_ext
        if (g_file_ext != ".ui"):
                self.label_2.setText("Неверное расширение файла")
        else:
                name = self.lineEdit.text()
                if (name == ""):
                        self.label_2.setText("Не задано имя скрипта .py")
                else:
                        pyname = name + ".py"
                        if (os.system(f'pyuic5 -x {g_file_path} -o {pyname}') == 0):
                                self.label_2.setText(f'Успешно конвертировано в .py файл {pyname}')
                        else:
                                self.label_2.setText(f'Ошибка конвертации в .py файл {pyname}')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())
